services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zoo1

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    hostname: kafka-schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,OPTIONS
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - zoo1
      - kafka1
  
  schema-registry-ui:
    image: landoop/schema-registry-ui:0.9.5
    hostname: kafka-schema-registry-ui
    ports:
      - "8001:8000"
    environment:
      SCHEMAREGISTRY_URL: http://kafka-schema-registry:8081
      PROXY: "true"
    depends_on:
      - kafka-schema-registry
  
  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:7.6.0
    hostname: kafka-rest-proxy
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
    depends_on:
      - zoo1
      - kafka1
      - kafka-schema-registry
  
  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    hostname: kafka-topics-ui
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      PROXY: "true"
    depends_on:
      - zoo1
      - kafka1
      - kafka-schema-registry
      - kafka-rest-proxy

  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore

  order-microservice:
    image: online-store/order-microservice:0.0.1
    container_name: order-microservice
    hostname: order-microservice
    #restart: on-failure
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/bookstore"
      SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
      BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
      DATABASE_USER: bookstore
      DATABASE_PASSWORD: bookstore
      SECURITY_PROTOCOL: PLAINTEXT
      SASL_MECHANISM: PLAIN
    build:
      context: order-microservice
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "1080:8080"
    depends_on:
      - postgres
      - kafka1
      - kafka-schema-registry

  inventory-microservice:
    image: online-store/inventory-microservice:0.0.2
    container_name: inventory-microservice
    hostname: inventory-microservice
    #restart: on-failure
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/bookstore"
      SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
      BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
      DATABASE_USER: bookstore
      DATABASE_PASSWORD: bookstore
      SECURITY_PROTOCOL: PLAINTEXT
      SASL_MECHANISM: PLAIN
    build:
      context: inventory-microservice
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - kafka1
      - kafka-schema-registry

  kafkacat:
    image: confluentinc/cp-kafkacat
    command: sleep infinity

volumes:
  postgres:
    driver:
      local

networks:
  default:
    driver: bridge
    name: bookstore-network