server:
  port: ${PORT:8083}

kafka:
  topic:
    order: "book-order"
    product: "product"
    order-stock: "order-stock"

spring:
  application:
    name: product-master
  kafka:
    # Required connection configs for Kafka producer, consumer, and admin
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    # Required connection configs for Confluent Cloud Schema Registry
    properties:
      stream-properties:
        schema.registry.url: ${SCHEMA_HOST}
        bootstrap.servers: ${BOOTSTRAP_SERVERS}
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      schema.registry.url: ${SCHEMA_HOST}
      security.protocol: PLAINTEXT
      sasl.mechanism: PLAIN
      credentials.source: USER_INFO
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      isolation-level: read_committed
      auto-offset-reset: none
      enable-auto-commit: false
      properties:
        auto.offset.reset: earliest
        specific.protobuf.key.type: java.lang.String
        specific.protobuf.value.type: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        allow.auto.create.topics: 'false'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
  output.ansi.enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: product
    password: product
    hikari:
      auto-commit: false
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      open-in-view: false
      hibernate:
        connection:
          provider_disables_autocommit: true
        temp:
          use_jdbc_metadata_defaults: false


product-sample-data-path: data/products.txt

logging:
  pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"
  level:
    org.apache.kafka.streams.kstream: INFO
    org.springframework.data: DEBUG
    org.springframework.boot.autoconfigure: ERROR
    org.hibernate: DEBUG