spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: bookstore
    password: bookstore
  jpa:
    show-sql: true
    generate-ddl: true
  kafka:
    # Required connection configs for Kafka producer, consumer, and admin
    bootstrap-servers: "PLAINTEXT://localhost:9094"
    # Required connection configs for Confluent Cloud Schema Registry
    properties:
      schema.registry.url: "http://localhost:8081"
      security.protocol: "PLAINTEXT"
      sasl.mechanism: "PLAIN"

logging:
  level:
    org.springframework.data: DEBUG