server:
  port: ${PORT:8083}

spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
