spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: product-tx-
      properties:
        enable.idempotence: true
    streams:
      cleanup:
        on-shutdown: false