server:
  port: ${PORT:8084}

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate.id.new_generator_mappings: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: secset
