server:
  port: ${PORT:8082}

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: secset

logging:
  level:
    org.springframework.data: DEBUG
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.web.reactive: DEBUG