server:
  port: ${PORT:8082}

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: secset

  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 5000
      bindings:
        input:
          consumer:
            max-attempts: 1
          destination: myDestination
          group: consumerGroup