server:
  error:
    include-message: always
    include-binding-errors: always
  port: ${PORT:8085}

kafka:
  #topics:
  topic:
    id: "book-order-id"
    name: "book-order"
    group-id: "order-processor-group"

spring:
  application:
    name: order-microservice
  kafka:
    admin:
      properties:
        min-in-sync-replicas: 1
    # Required connection configs for Kafka producer, consumer, and admin
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    # Required connection configs for Confluent Cloud Schema Registry
    properties:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      security.protocol: PLAINTEXT
      schema.registry.url: ${SCHEMA_HOST}
      sasl.mechanism: PLAIN
      credentials.source: USER_INFO
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      isolation-level: read_committed
      auto-offset-reset: none
      enable-auto-commit: false
      properties:
        auto.offset.reset: earliest
        specific.protobuf.key.type: java.lang.String
        specific.protobuf.value.type: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        allow.auto.create.topics: 'false'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
  output.ansi.enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: product
    password: product
    hikari:
      auto-commit: false
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      open-in-view: false
      hibernate:
        connection:
          provider_disables_autocommit: true
        temp:
          use_jdbc_metadata_defaults: false
      datasource:
        url: jdbc:postgresql://localhost:5432/product
        username: postgres
        password: postgres


logging:
  pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"
  level:
    org.springframework.data: INFO
    org.springframework.boot.autoconfigure: ERROR
    org.hibernate: INFO