server:
  error:
    include-message: always
    include-binding-errors: always
  port: ${PORT:8080}

spring:
  active:
    profile: local
  application:
    name: order-microservice
  kafka:
    bootstrap-servers: PLAINTEXT://localhost:9092
    # Required connection configs for Confluent Cloud Schema Registry
    properties:
      schema.registry.url: http://localhost:8081
      security.protocol: PLAINTEXT
      sasl.mechanism: PLAIN
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      isolation-level: read_committed
      auto-offset-reset: none
      enable-auto-commit: false
      properties:
        specific.protobuf.value.type: com.metao.book.order.OrderPaymentEvent
        auto.offset.reset: earliest
        allow.auto.create.topics: 'false'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
      properties:
        enable.idempotence: true
  output.ansi.enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: bookstore
    password: bookstore
    hikari:
      auto-commit: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    outOfOrder: false
    locations: classpath:db/migration
    clean-disabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      open-in-view: false
      hibernate:
        connection:
          provider_disables_autocommit: true
        temp:
          use_jdbc_metadata_defaults: false

kafka:
  topic:
    order-created:
      id: "order-created-id"
      name: "order-created"
      group-id: "order-created-group"
    order-payment:
      id: "order-payment-id"
      name: "order-payment"
      group-id: "order-payment-group"

logging:
  pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%20.20t]){yellow} %clr(:){red} %clr(%m){faint}%n"
  level:
    org.springframework.data: INFO
    org.springframework.boot.autoconfigure: ERROR
    org.hibernate: INFO