server:
  port: ${PORT:8081}

spring:
  application:
    name: api-gateway

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

info:
  app:
    name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info