server:
  port: ${PORT:8081}
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  cloud:
    gateway:
      default-filters:
        - name: SCGWGlobalFilter
      routes:
        - id: product-route
          uri: lb://product-ms/
          predicates:
            - Path=/products/**
          filters:
            - name: ThrottleGatewayFilter
              args:
                capacity: 12
                refillTokens: 1
                refillPeriod: 10


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

info:
  app:
    name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG