server:
  port: ${PORT:8081}

spring:
  cloud:
    gateway:
      default-filters:
        - name: SCGWGlobalFilter
      routes:
        # =================RETAILS MICROSERVICE========================
        - id: product-route
          uri: lb://product-ms
          predicates:
            - Path=/products/**
          filters:
            - name: ThrottleGatewayFilter
              args:
                capacity: 120
                refillTokens: 100
                refillPeriod: 1
        # =================CART MICROSERVICE========================
        - id: cart-route
          uri: lb://cart-ms
          predicates:
            - Path=/cart/**
        # =================CHECKOUT MICROSERVICE====================
        - id: checkout-route
          uri: lb://checkout-ms
          predicates:
            - Path=/checkout/**


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG