server:
  port: ${PORT:8081}
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  cloud:
    gateway:
      routes:
        - id: product-ms
          uri: http://localhost:8082/
          predicates:
            - Path=/product-ms/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

info:
  app:
    name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
