name: Java CI with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish the shared-kernel to maven
        run: gradle publishToMavenLocal
      - name: Build microservices and run tests with Gradle
        run: gradle clean build